version: '3.7'

volumes:
  logs:
    driver: local

networks:
  app:

services:
  nginx:
    build:
      context: ../..
      dockerfile: docker/dev/nginx/Dockerfile
    ports:
      - 8080:80
    networks:
      app:

  php-fpm:
    build:
      context: ../..
      dockerfile: docker/dev/php-fpm/Dockerfile
    networks:
      app:

  php-workers:
    build:
      context: ../..
      dockerfile: docker/dev/php-workers/Dockerfile
    networks:
      app:

  rabbitmq:
    build:
      context: ../..
      dockerfile: docker/dev/rabbitmq/Dockerfile
    ports:
      - 15672:15672
    networks:
      app:

  mysql:
    build:
      context: ../..
      dockerfile: docker/dev/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: 'db_password'
      MYSQL_ROOT_PASSWORD: 'db_password_root'
    ports:
      - 3306:3306
    networks:
      app:

  redis:
    build:
      context: ../..
      dockerfile: docker/dev/redis/Dockerfile
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: 'redis_password'
    networks:
      app:
